<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DonorList.aspx.cs" Inherits="BloodManagementSystemAspDotNet.DonorList" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Donor List - Blood Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body class="bg-light">

    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="#">🩸 Blood Management</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="AddDonor.aspx">Add Donor</a></li>
                    <li class="nav-item"><a class="nav-link" href="DonorList.aspx">Donor List</a></li>
                    <li class="nav-item"><a class="nav-link" href="SearchDonor.aspx">Search Donor</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <form id="form1" runat="server" class="container mt-5">
        <div class="card shadow-lg p-4">
            <h2 class="text-center text-danger mb-4">📋 Donor List</h2>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                CssClass="table table-bordered table-hover text-center"
                AutoGenerateDeleteButton="True"
                OnRowDeleting="GridView1_RowDeleting">
                <HeaderStyle CssClass="table-danger" />
                <Columns>
                    <asp:BoundField DataField="DonorId" HeaderText="Donor ID" />
                    <asp:BoundField DataField="DonorName" HeaderText="Donor Name" />
                    <asp:BoundField DataField="Age" HeaderText="Age" />
                    <asp:BoundField DataField="Gender" HeaderText="Gender" />
                    <asp:BoundField DataField="BloodGroup" HeaderText="Blood Group" />
                    <asp:BoundField DataField="City" HeaderText="City" />
                    <asp:BoundField DataField="Phone" HeaderText="Phone" />
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
